services:
  # A web service for the Streamlit app
  - type: web
    name: metal-price-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app2.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    plan: free